DadosSocioEconomicos.MVC/Controllers/CalculadoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DadosSocioEconomicos.Data.Contexto;
using DadosSocioEconomicos.Entidades.Entidades;

namespace DadosSocioEconomicos.MVC.Controllers
{
    public class CalculadoraController : Controller
    {
        private readonly Contexto _context;

        public CalculadoraController(Contexto context)
        {
            _context = context;
        }

        // GET: Calculadora
        public async Task<IActionResult> Index()
        {

            return View(await _context.Nacoes.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind("Id,Nome,Populacao,PIB,IDH")] Nacao nacao)
        {

            return View();
        }

        // GET: Calculadora/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nacao = await _context.Nacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nacao == null)
            {
                return NotFound();
            }

            return View(nacao);
        }

        // GET: Calculadora/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Calculadora/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Populacao,PIB,IDH")] Nacao nacao)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nacao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nacao);
        }

        // GET: Calculadora/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nacao = await _context.Nacoes.FindAsync(id);
            if (nacao == null)
            {
                return NotFound();
            }
            return View(nacao);
        }

        // POST: Calculadora/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Populacao,PIB,IDH")] Nacao nacao)
        {
            if (id != nacao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NacaoExists(nacao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nacao);
        }

        // GET: Calculadora/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nacao = await _context.Nacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nacao == null)
            {
                return NotFound();
            }

            return View(nacao);
        }

        // POST: Calculadora/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nacao = await _context.Nacoes.FindAsync(id);
            _context.Nacoes.Remove(nacao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NacaoExists(int id)
        {
            return _context.Nacoes.Any(e => e.Id == id);
        }
    }
}

DadosSocioEconomicos.MVC/Controllers/NacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DadosSocioEconomicos.Data.Contexto;
using DadosSocioEconomicos.Entidades.Entidades;
using DadosSocioEconomicos.MVC.Models;

namespace DadosSocioEconomicos.MVC.Controllers
{
    public class NacoesController : Controller
    {
        private readonly Contexto _context;

        public NacoesController(Contexto context)
        {
            _context = context;
        }

        public List<SelectListItem> MontaDropDownListPaises()
        {
            List<Nacao> nacoes = _context.Nacoes.ToList();
            List<string> listaNomes = new List<string>();
            List<SelectListItem> items = new List<SelectListItem>();

            foreach (Nacao nacao in nacoes)
            {
                listaNomes.Add(nacao.Nome);
            }

            int n = listaNomes.Count();

            for (int i = 0; i < n; i++)
            {
                if (i == 0)
                {
                    items.Add(new SelectListItem { Value = listaNomes[i], Text = listaNomes[i],  Selected = true });
                }
                else { items.Add(new SelectListItem { Value = listaNomes[i], Text = listaNomes[i]  }); }
            }
            return items;
        }

        public List<string> MontaListaPaises()
        {
            List<Nacao> nacoes = _context.Nacoes.ToList();
            List<string> listaNomes = new List<string>();
            foreach (Nacao nacao in nacoes)
            {
                listaNomes.Add(nacao.Nome);
            }

            return listaNomes;
        }

        public List<string> MontaDropDownListNomePaises()
        {
            List<Nacao> nacoes = _context.Nacoes.ToList();
            List<string> listaNomes = new List<string>();
            
            foreach (Nacao nacao in nacoes)
            {
                listaNomes.Add(nacao.Nome);
            }
            return listaNomes;
        }

        public List<SelectListItem> MontaDropDownListIndicadores()
        {
            List<SelectListItem> indicadores = new List<SelectListItem>
            {
                new SelectListItem { Text = "População", Value = "0", Selected = true },
                new SelectListItem { Text = "PIB", Value = "1" },
                new SelectListItem { Text = "IDH", Value = "2" }
            };
            return indicadores;
        }

        // GET: Nacoes
        public IActionResult Grafico()
        {
            return View();
        }

        public IActionResult ComparativoDuas()
        {
            var listaPaises = MontaDropDownListPaises();
            List<SelectListItem> listaIndicadores = MontaDropDownListIndicadores();

            ViewBag.Paises = listaPaises;
            ViewBag.Indicadores = listaIndicadores;


            return View();
        }

        [HttpPost]
        public IActionResult ComparativoDuas([Bind("PrimeiraNacao,SegundaNacao,Indicador")] Comparativo comparativo)
        {
            var listaDePaises = MontaDropDownListPaises();
            ViewBag.Paises = listaDePaises;
            var listaPaises = MontaListaPaises();
            string nomeIndicador = comparativo.Indicador;
            string nome = "";
            decimal d1 = 0;
            decimal d2 = 0;
            Nacao Pais1 = _context.Nacoes.Where(m => m.Nome == comparativo.PrimeiraNacao).FirstOrDefault();
            Nacao Pais2 = _context.Nacoes.Where(m => m.Nome == comparativo.SegundaNacao).FirstOrDefault();

            if (nomeIndicador == "Populacao")
            {
                d1 = Pais1.Populacao;
                d2 = Pais2.Populacao;
                nome = "Análise da população";
            }
            if (nomeIndicador == "PIB")
            {
                d1 = Pais1.PIB;
                d2 = Pais2.PIB;
                nome = "Análise do PIB";
            }
            if (nomeIndicador == "IDH")
            {
                d1 = Pais1.IDH;
                d2 = Pais2.IDH;
                nome = "Análise do IDH";
            }

            var eixoX = new List<string>();
            var eixoY = new List<decimal>();

            eixoX.Add(Pais1.Nome);
            eixoY.Add(d1);
            eixoX.Add(Pais2.Nome);
            eixoY.Add(d2);

            ViewBag.EixoX = eixoX.ToList();
            ViewBag.EixoY = eixoY.ToList();
            ViewBag.Nome = nome;

            ViewData["ListaNacoes"] = new SelectList(listaPaises);

            return View();
        }

        public ActionResult ComparativoGeral()
        {
            return View();
        }

        public ActionResult ComparativoGenerico()
        {
            var listaDePaises = MontaDropDownListPaises();
            ViewBag.Paises = listaDePaises;
            return View();
        }

        [HttpPost]
        public ActionResult ComparativoGenerico([Bind("ListaNacoes,Indicador")] NacoesGeral nacoes)
        {
            var listaDePaises = MontaDropDownListPaises();
            string indicador = nacoes.Indicador;
            string[] listaNomes = nacoes.ListaNacoes;
            int qtdPaises = listaNomes.Length;

            for (int i = 0; i < qtdPaises; i++)
            {

            }

            ViewBag.Paises = listaDePaises;

            return View();
        }

        [HttpPost]
        public  ActionResult ComparativoGeral([Bind("Dado")] Indicador indicador)
        {
            string nomeIndicador = indicador.Dado;
            string nome = "";
            List<Nacao> nacoes = _context.Nacoes.ToList();
            var eixoX = new List<string>();
            var eixoY = new List<decimal>();

            foreach(Nacao nacao in nacoes)
            {
                eixoX.Add(nacao.Nome);

                if (nomeIndicador == "Populacao") { eixoY.Add(nacao.Populacao); }
                
                if (nomeIndicador == "IDH") { eixoY.Add(nacao.IDH); }

                if (nomeIndicador == "PIB") { eixoY.Add(nacao.PIB); }

            }

            if (nomeIndicador == "Populacao") { nome = "Análise da população"; }

            if (nomeIndicador == "IDH") { nome = "Análise do IDH"; }

            if (nomeIndicador == "PIB") { nome = "Análise do PIB"; }

            ViewBag.EixoX = eixoX.ToList();
            ViewBag.EixoY = eixoY.ToList();
            ViewBag.Nome = nome;
            return View();
        }

        // GET: Nacoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Nacoes.ToListAsync());
        }

        // GET: Nacoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nacao = await _context.Nacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nacao == null)
            {
                return NotFound();
            }

            return View(nacao);
        }

        // GET: Nacoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Nacoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Populacao,PIB,IDH")] Nacao nacao)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nacao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nacao);
        }

        // GET: Nacoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nacao = await _context.Nacoes.FindAsync(id);
            if (nacao == null)
            {
                return NotFound();
            }
            return View(nacao);
        }

        // POST: Nacoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Populacao,PIB,IDH")] Nacao nacao)
        {
            if (id != nacao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NacaoExists(nacao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nacao);
        }

        // GET: Nacoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nacao = await _context.Nacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nacao == null)
            {
                return NotFound();
            }

            return View(nacao);
        }

        // POST: Nacoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

DadosSocioEconomicos.MVC/Views/Calculadora/Create.cshtml
@model DadosSocioEconomicos.Entidades.Entidades.Nacao

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Nacao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Populacao" class="control-label"></label>
                <input asp-for="Populacao" class="form-control" />
                <span asp-validation-for="Populacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PIB" class="control-label"></label>
                <input asp-for="PIB" class="form-control" />
                <span asp-validation-for="PIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDH" class="control-label"></label>
                <input asp-for="IDH" class="form-control" />
                <span asp-validation-for="IDH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DadosSocioEconomicos.MVC/Views/Calculadora/Delete.cshtml
@model DadosSocioEconomicos.Entidades.Entidades.Nacao

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Populacao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Populacao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PIB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PIB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IDH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IDH)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DadosSocioEconomicos.MVC/Views/Calculadora/Details.cshtml
@model DadosSocioEconomicos.Entidades.Entidades.Nacao

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Nacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Populacao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Populacao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PIB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PIB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IDH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IDH)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DadosSocioEconomicos.MVC/Views/Calculadora/Edit.cshtml
@model DadosSocioEconomicos.Entidades.Entidades.Nacao

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Nacao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Populacao" class="control-label"></label>
                <input asp-for="Populacao" class="form-control" />
                <span asp-validation-for="Populacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PIB" class="control-label"></label>
                <input asp-for="PIB" class="form-control" />
                <span asp-validation-for="PIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDH" class="control-label"></label>
                <input asp-for="IDH" class="form-control" />
                <span asp-validation-for="IDH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DadosSocioEconomicos.MVC/Views/Calculadora/Index.cshtml
@model IEnumerable<DadosSocioEconomicos.Entidades.Entidades.Nacao>

@{
    ViewData["Title"] = "Index";
}

<h2>Calcular índices financeiros e estatísticos</h2>

<div class="row">
    <div class="col-md-3">
        <h4>Opções</h4>
        <ul>
            <li><a asp-controller="Nacoes" asp-action="Index">Ver nações cadastradas</a></li>
            <li><a asp-controller="Nacoes" asp-action="Create">Cadastrar nova nação</a></li>
            <li><a asp-controller="Nacoes" asp-action="Grafico">Ver análises gráficas</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h4>Fórmulas de calcular</h4>
        <ul>
            <li><a data-toggle="modal" href="#myModal1">Média aritimética amostral</a></li>
            <li><a data-toggle="modal" href="#myModal2">Desvio padrão amostral</a></li>
            <li><a data-toggle="modal" href="#myModal3">PIB per capita</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h4>Cálculos estatísticos</h4>
        <ul>
            <li>Média aritimética amostral</li>
            <li>Desvio padrão amostral</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h4>Cálculos financeiros</h4>
        <ul>
            <li>PIB per capita</li>
        </ul>
    </div>
</div>

<form asp-action="Calcular">
    <div class="row">
        <div class="col-md-3">
            <table class="table">
                <thead>
                    <tr>
                        <th style="text-align:center">Selecione os países</th>
                        <th>
                            @Html.DisplayNameFor(model => model.Nome)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="text-align:center">@Html.CheckBox("check", false)</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-3" style="vertical-align:central;text-align:center">
            <img src="~/images/bandeiras.jpg" alt="ASP.NET" class="img-responsive" />
        </div>
    </div>
    
</form>

<!-- Modal -->
<div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Média aritimética</h4>
            </div>
            <div class="modal-body">
                <img src="~/images/media.png" alt="ASP.NET" class="img-responsive" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Desvio padrão</h4>
            </div>
            <div class="modal-body">
                <img src="~/images/desviopadrao.png" alt="ASP.NET" class="img-responsive" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="myModal3" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">PIB per capita</h4>
            </div>
            <div class="modal-body">
                <img src="~/images/ppc.png" alt="ASP.NET" class="img-responsive" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>